# Generated by Django 4.2 on 2023-04-09 18:37

from django.db import migrations, models
import perfis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
                'db_table': 'perfis',
                'managed': True,
            },
            managers=[
                ('objects', perfis.models.PerfilManager()),
            ],
        ),
    ]
